export interface VehicleModel {
  make: string;
  model: string;
  slug: string;
  brandSlug: string;
  modelSlug: string;
  urlPath: string;
  years: number[];
  latestYear: number;
  vehicleCount: number;
  priceRange: {
    min: number;
    max: number;
  };
  rangeMin: number;
  rangeMax: number;
  connectors: string[];
  featured?: boolean;
}

export const models: VehicleModel[] = [
  {
    make: "BMW",
    model: "i4",
    slug: "bmw-i4",
    brandSlug: "bmw",
    modelSlug: "i4",
    urlPath: "/vehicles/bmw/i4",
    years: [2026],
    latestYear: 2026,
    vehicleCount: 1,
    priceRange: { min: 59400, max: 64400 },
    rangeMin: 301,
    rangeMax: 301,
    connectors: ["NACS"],
  },
  {
    make: "BMW",
    model: "iX",
    slug: "bmw-ix",
    brandSlug: "bmw",
    modelSlug: "ix",
    urlPath: "/vehicles/bmw/ix",
    years: [2026],
    latestYear: 2026,
    vehicleCount: 1,
    priceRange: { min: 88895, max: 93895 },
    rangeMin: 324,
    rangeMax: 324,
    connectors: ["NACS"],
  },
  {
    make: "Chevrolet",
    model: "Blazer EV",
    slug: "chevrolet-blazer-ev",
    brandSlug: "chevrolet",
    modelSlug: "blazer-ev",
    urlPath: "/vehicles/chevrolet/blazer-ev",
    years: [2024],
    latestYear: 2024,
    vehicleCount: 1,
    priceRange: { min: 56715, max: 61715 },
    rangeMin: 293,
    rangeMax: 293,
    connectors: ["CCS1"],
  },
  {
    make: "Chevrolet",
    model: "Equinox EV",
    slug: "chevrolet-equinox-ev",
    brandSlug: "chevrolet",
    modelSlug: "equinox-ev",
    urlPath: "/vehicles/chevrolet/equinox-ev",
    years: [2026, 2025],
    latestYear: 2026,
    vehicleCount: 5,
    priceRange: { min: 33600, max: 47800 },
    rangeMin: 285,
    rangeMax: 319,
    connectors: ["NACS"],
    featured: true,
  },
  {
    make: "Subaru",
    model: "Solterra",
    slug: "subaru-solterra",
    brandSlug: "subaru",
    modelSlug: "solterra",
    urlPath: "/vehicles/subaru/solterra",
    years: [2026, 2025, 2024, 2023],
    latestYear: 2026,
    vehicleCount: 7,
    priceRange: { min: 38495, max: 45555 },
    rangeMin: 278,
    rangeMax: 288,
    connectors: ["NACS"],
    featured: true,
  },
  {
    make: "Ford",
    model: "F-150 Lightning",
    slug: "ford-f-150-lightning",
    brandSlug: "ford",
    modelSlug: "f-150-lightning",
    urlPath: "/vehicles/ford/f-150-lightning",
    years: [2026, 2025, 2024],
    latestYear: 2026,
    vehicleCount: 7,
    priceRange: { min: 49875, max: 87090 },
    rangeMin: 240,
    rangeMax: 320,
    connectors: ["NACS"],
    featured: true,
  },
  {
    make: "Ford",
    model: "Mustang Mach-E",
    slug: "ford-mustang-mach-e",
    brandSlug: "ford",
    modelSlug: "mustang-mach-e",
    urlPath: "/vehicles/ford/mustang-mach-e",
    years: [2024],
    latestYear: 2024,
    vehicleCount: 1,
    priceRange: { min: 46995, max: 51995 },
    rangeMin: 312,
    rangeMax: 312,
    connectors: ["CCS1"],
    featured: true,
  },
  {
    make: "Genesis",
    model: "GV60",
    slug: "genesis-gv60",
    brandSlug: "genesis",
    modelSlug: "gv60",
    urlPath: "/vehicles/genesis/gv60",
    years: [2026],
    latestYear: 2026,
    vehicleCount: 1,
    priceRange: { min: 56500, max: 61500 },
    rangeMin: 294,
    rangeMax: 294,
    connectors: ["NACS"],
  },
  {
    make: "Genesis",
    model: "GV70 Electrified",
    slug: "genesis-gv70-electrified",
    brandSlug: "genesis",
    modelSlug: "gv70-electrified",
    urlPath: "/vehicles/genesis/gv70-electrified",
    years: [2026],
    latestYear: 2026,
    vehicleCount: 1,
    priceRange: { min: 67950, max: 72950 },
    rangeMin: 282,
    rangeMax: 282,
    connectors: ["NACS"],
  },
  {
    make: "Honda",
    model: "Prologue",
    slug: "honda-prologue",
    brandSlug: "honda",
    modelSlug: "prologue",
    urlPath: "/vehicles/honda/prologue",
    years: [2026],
    latestYear: 2026,
    vehicleCount: 1,
    priceRange: { min: 56650, max: 61650 },
    rangeMin: 296,
    rangeMax: 296,
    connectors: ["NACS"],
  },
  {
    make: "Hyundai",
    model: "IONIQ 5",
    slug: "hyundai-ioniq-5",
    brandSlug: "hyundai",
    modelSlug: "ioniq-5",
    urlPath: "/vehicles/hyundai/ioniq-5",
    years: [2026, 2024],
    latestYear: 2026,
    vehicleCount: 10,
    priceRange: { min: 35000, max: 67000 },
    rangeMin: 221,
    rangeMax: 318,
    connectors: ["NACS"],
    featured: true,
  },
  {
    make: "Kia",
    model: "EV6",
    slug: "kia-ev6",
    brandSlug: "kia",
    modelSlug: "ev6",
    urlPath: "/vehicles/kia/ev6",
    years: [2025, 2024, 2023, 2022],
    latestYear: 2025,
    vehicleCount: 18,
    priceRange: { min: 42115, max: 63800 },
    rangeMin: 206,
    rangeMax: 319,
    connectors: ["NACS", "CCS1"],
    featured: true,
  },
  {
    make: "Kia",
    model: "EV9",
    slug: "kia-ev9",
    brandSlug: "kia",
    modelSlug: "ev9",
    urlPath: "/vehicles/kia/ev9",
    years: [2026],
    latestYear: 2026,
    vehicleCount: 5,
    priceRange: { min: 54900, max: 71900 },
    rangeMin: 230,
    rangeMax: 305,
    connectors: ["NACS"],
    featured: true,
  },
  {
    make: "Mercedes-Benz",
    model: "EQE SUV",
    slug: "mercedes-benz-eqe-suv",
    brandSlug: "mercedes-benz",
    modelSlug: "eqe-suv",
    urlPath: "/vehicles/mercedes-benz/eqe-suv",
    years: [2026],
    latestYear: 2026,
    vehicleCount: 1,
    priceRange: { min: 85550, max: 90550 },
    rangeMin: 285,
    rangeMax: 285,
    connectors: ["NACS"],
  },
  {
    make: "Mercedes-Benz",
    model: "EQS SUV",
    slug: "mercedes-benz-eqs-suv",
    brandSlug: "mercedes-benz",
    modelSlug: "eqs-suv",
    urlPath: "/vehicles/mercedes-benz/eqs-suv",
    years: [2026],
    latestYear: 2026,
    vehicleCount: 1,
    priceRange: { min: 110250, max: 115250 },
    rangeMin: 332,
    rangeMax: 332,
    connectors: ["NACS"],
  },
  {
    make: "Nissan",
    model: "Ariya",
    slug: "nissan-ariya",
    brandSlug: "nissan",
    modelSlug: "ariya",
    urlPath: "/vehicles/nissan/ariya",
    years: [2024],
    latestYear: 2024,
    vehicleCount: 1,
    priceRange: { min: 47490, max: 52490 },
    rangeMin: 304,
    rangeMax: 304,
    connectors: ["CCS1"],
  },
  {
    make: "Rivian",
    model: "R1S",
    slug: "rivian-r1s",
    brandSlug: "rivian",
    modelSlug: "r1s",
    urlPath: "/vehicles/rivian/r1s",
    years: [2026],
    latestYear: 2026,
    vehicleCount: 1,
    priceRange: { min: 78000, max: 83000 },
    rangeMin: 330,
    rangeMax: 330,
    connectors: ["NACS"],
  },
  {
    make: "Rivian",
    model: "R1T",
    slug: "rivian-r1t",
    brandSlug: "rivian",
    modelSlug: "r1t",
    urlPath: "/vehicles/rivian/r1t",
    years: [2024],
    latestYear: 2024,
    vehicleCount: 1,
    priceRange: { min: 73000, max: 78000 },
    rangeMin: 330,
    rangeMax: 330,
    connectors: ["NACS"],
    featured: true,
  },
  {
    make: "Tesla",
    model: "Model 3",
    slug: "tesla-model-3",
    brandSlug: "tesla",
    modelSlug: "model-3",
    urlPath: "/vehicles/tesla/model-3",
    years: [2026, 2024],
    latestYear: 2026,
    vehicleCount: 6,
    priceRange: { min: 38630, max: 56630 },
    rangeMin: 298,
    rangeMax: 363,
    connectors: ["NACS"],
    featured: true,
  },
  {
    make: "Tesla",
    model: "Model Y",
    slug: "tesla-model-y",
    brandSlug: "tesla",
    modelSlug: "model-y",
    urlPath: "/vehicles/tesla/model-y",
    years: [2026, 2024],
    latestYear: 2026,
    vehicleCount: 6,
    priceRange: { min: 41630, max: 59130 },
    rangeMin: 306,
    rangeMax: 357,
    connectors: ["NACS"],
    featured: true,
  },
  {
    make: "Volkswagen",
    model: "ID.4",
    slug: "volkswagen-id.4",
    brandSlug: "volkswagen",
    modelSlug: "id-4",
    urlPath: "/vehicles/volkswagen/id-4",
    years: [2024],
    latestYear: 2024,
    vehicleCount: 1,
    priceRange: { min: 44995, max: 49995 },
    rangeMin: 275,
    rangeMax: 275,
    connectors: ["CCS1"],
  },
  {
    make: "Volkswagen",
    model: "ID. Buzz",
    slug: "volkswagen-id-buzz",
    brandSlug: "volkswagen",
    modelSlug: "id-buzz",
    urlPath: "/vehicles/volkswagen/id-buzz",
    years: [2024],
    latestYear: 2024,
    vehicleCount: 1,
    priceRange: { min: 61545, max: 65545 },
    rangeMin: 234,
    rangeMax: 234,
    connectors: ["CCS1"],
  },
  {
    make: "Tesla",
    model: "Cybertruck",
    slug: "tesla-cybertruck",
    brandSlug: "tesla",
    modelSlug: "cybertruck",
    urlPath: "/vehicles/tesla/cybertruck",
    years: [2024, 2026],
    latestYear: 2026,
    vehicleCount: 2,
    priceRange: { min: 79990, max: 79990 },
    rangeMin: 340,
    rangeMax: 340,
    connectors: ["NACS"],
    featured: true,
  },
  {
    make: "Cadillac",
    model: "Lyriq",
    slug: "cadillac-lyriq",
    brandSlug: "cadillac",
    modelSlug: "lyriq",
    urlPath: "/vehicles/cadillac/lyriq",
    years: [2024, 2026],
    latestYear: 2026,
    vehicleCount: 2,
    priceRange: { min: 57195, max: 63590 },
    rangeMin: 314,
    rangeMax: 314,
    connectors: ["CCS1", "NACS"],
  },
  {
    make: "Audi",
    model: "Q4 e-tron",
    slug: "audi-q4-etron",
    brandSlug: "audi",
    modelSlug: "q4-etron",
    urlPath: "/vehicles/audi/q4-etron",
    years: [2024],
    latestYear: 2024,
    vehicleCount: 1,
    priceRange: { min: 56800, max: 60800 },
    rangeMin: 265,
    rangeMax: 265,
    connectors: ["CCS1"],
  },
  {
    make: "Polestar",
    model: "2",
    slug: "polestar-2",
    brandSlug: "polestar",
    modelSlug: "2",
    urlPath: "/vehicles/polestar/2",
    years: [2024],
    latestYear: 2024,
    vehicleCount: 1,
    priceRange: { min: 51200, max: 56200 },
    rangeMin: 270,
    rangeMax: 270,
    connectors: ["CCS1"],
  },
  {
    make: "Polestar",
    model: "3",
    slug: "polestar-3",
    brandSlug: "polestar",
    modelSlug: "3",
    urlPath: "/vehicles/polestar/3",
    years: [2026],
    latestYear: 2026,
    vehicleCount: 1,
    priceRange: { min: 73400, max: 78400 },
    rangeMin: 315,
    rangeMax: 315,
    connectors: ["NACS"],
  },
  {
    make: "Lucid",
    model: "Air",
    slug: "lucid-air",
    brandSlug: "lucid",
    modelSlug: "air",
    urlPath: "/vehicles/lucid/air",
    years: [2024],
    latestYear: 2024,
    vehicleCount: 1,
    priceRange: { min: 69900, max: 74900 },
    rangeMin: 420,
    rangeMax: 420,
    connectors: ["CCS1"],
    featured: true,
  },
  {
    make: "Porsche",
    model: "Taycan",
    slug: "porsche-taycan",
    brandSlug: "porsche",
    modelSlug: "taycan",
    urlPath: "/vehicles/porsche/taycan",
    years: [2024],
    latestYear: 2024,
    vehicleCount: 1,
    priceRange: { min: 109650, max: 119650 },
    rangeMin: 225,
    rangeMax: 225,
    connectors: ["CCS1"],
  },
  {
    make: "Toyota",
    model: "bZ",
    slug: "toyota-bz",
    brandSlug: "toyota",
    modelSlug: "bz",
    urlPath: "/vehicles/toyota/bz",
    years: [2026],
    latestYear: 2026,
    vehicleCount: 1,
    priceRange: { min: 44420, max: 50000 },
    rangeMin: 236,
    rangeMax: 314,
    connectors: ["NACS"],
  },
];
